#!/usr/bin/env python3
"""
Parser for Bounty Alert issues generated by BountyScout.
Extracts structured opportunity data from the issue body.
"""

import re
import json
import sys
from typing import List, Dict, Optional

def parse_bounty_alert(issue_body: str) -> List[Dict[str, Optional[str]]]:
    """
    Parse a bounty alert issue body and return a list of opportunities.
    
    Each opportunity is a dict with keys:
    - index: int
    - title: str
    - url: str
    - repository: str
    - comments: int
    - last_updated: str
    - bounty: Optional[str] (e.g., "$60" or None)
    """
    opportunities = []
    
    # Split by the "#### " header pattern
    blocks = re.split(r'\n#### \d+\.', issue_body)
    if not blocks:
        return opportunities
    
    # The first block is before the first entry (contains scan time, etc.) – skip it
    for block in blocks[1:]:
        block = block.strip()
        if not block:
            continue
            
        lines = block.splitlines()
        if not lines:
            continue
            
        # First line contains the title and URL
        title_line = lines[0].strip()
        # Extract URL from markdown link [title](url) or plain text
        url_match = re.search(r'\((https?://[^)]+)\)', title_line)
        url = url_match.group(1) if url_match else None
        
        # Clean title: remove any leading/trailing markdown artifacts
        title = re.sub(r'\s*\([^)]*\)\s*$', '', title_line).strip()
        # Remove any leading "Bounty: " prefix for consistency, but keep it in a separate field
        bounty_match = re.match(r'\[Bounty:\s*([^\]]+)\]', title)
        bounty = bounty_match.group(1) if bounty_match else None
        # Remove the bounty prefix from title if present
        title = re.sub(r'^\[Bounty:\s*[^\]]*\]\s*', '', title).strip()
        
        # Initialize fields
        repository = None
        comments = None
        last_updated = None
        
        # Parse the remaining lines for metadata
        for line in lines[1:]:
            line = line.strip()
            if line.startswith('- **Repository:**'):
                repo_match = re.search(r'\[(.*?)\]', line)
                repository = repo_match.group(1) if repo_match else line.split('**')[2].strip()
            elif line.startswith('- **Comments:**'):
                comments_match = re.search(r'(\d+)', line)
                comments = int(comments_match.group(1)) if comments_match else None
            elif line.startswith('- **Last Updated:**'):
                last_updated = line.split('**')[2].strip()
        
        # Determine index from the block position (original order)
        index = len(opportunities) + 1
        
        opportunities.append({
            'index': index,
            'title': title,
            'url': url,
            'repository': repository,
            'comments': comments,
            'last_updated': last_updated,
            'bounty': bounty
        })
    
    return opportunities

def main():
    """Read issue body from stdin or file and output JSON."""
    if len(sys.argv) > 1:
        with open(sys.argv[1], 'r', encoding='utf-8') as f:
            body = f.read()
    else:
        body = sys.stdin.read()
    
    opportunities = parse_bounty_alert(body)
    print(json.dumps(opportunities, indent=2, ensure_ascii=False))

if __name__ == '__main__':
    main()
