const { Octokit } = require('@octokit/rest');
const fs = require('fs').promises;
const path = require('path');

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

async function loadNewBounties() {
  try {
    const reportPath = path.join(__dirname, '..', 'data', 'new-bounties.json');
    const data = await fs.readFile(reportPath, 'utf8');
    return JSON.parse(data);
  } catch (error) {
    console.log('No new bounties report found');
    return null;
  }
}

function formatBountyList(bounties) {
  let body = '## 🎯 New Bounty Opportunities\n\n';
  body += `Found **${bounties.length}** new bounties!\n\n`;
  
  const byPlatform = {};
  bounties.forEach(bounty => {
    if (!byPlatform[bounty.platform]) {
      byPlatform[bounty.platform] = [];
    }
    byPlatform[bounty.platform].push(bounty);
  });
  
  for (const [platform, platformBounties] of Object.entries(byPlatform)) {
    body += `### ${platform} (${platformBounties.length})\n\n`;
    
    platformBounties.forEach(bounty => {
      body += `- **[${bounty.title}](${bounty.url})**\n`;
      if (bounty.repository) {
        body += `  - Repository: ${bounty.repository}\n`;
      }
      if (bounty.value) {
        body += `  - Value: $${bounty.value} USD\n`;
      }
      if (bounty.labels && bounty.labels.length > 0) {
        body += `  - Labels: ${bounty.labels.join(', ')}\n`;
      }
      body += `  - Created: ${new Date(bounty.created_at).toLocaleDateString()}\n`;
      body += '\n';
    });
  }
  
  body += '\n---\n';
  body += `*Last updated: ${new Date().toLocaleString()}*\n`;
  body += '*This issue was automatically generated by BountyScout*';
  
  return body;
}

async function createOrUpdateIssue(bounties) {
  try {
    const [owner, repo] = (process.env.GITHUB_REPOSITORY || 'dev-kp-eloper/BountyScout').split('/');
    
    const title = `🎯 Bounty Alert: ${bounties.length} New ${bounties.length === 1 ? 'Opportunity' : 'Opportunities'} Found`;
    const body = formatBountyList(bounties);
    
    // Check for existing open bounty alert issues
    const { data: existingIssues } = await octokit.issues.listForRepo({
      owner,
      repo,
      state: 'open',
      labels: 'bounty-alert',
      per_page: 1
    });
    
    if (existingIssues.length > 0) {
      // Update existing issue
      const issue = existingIssues[0];
      await octokit.issues.update({
        owner,
        repo,
        issue_number: issue.number,
        title,
        body
      });
      console.log(`✅ Updated issue #${issue.number}`);
    } else {
      // Create new issue
      const { data: newIssue } = await octokit.issues.create({
        owner,
        repo,
        title,
        body,
        labels: ['bounty-alert', 'automated']
      });
      console.log(`✅ Created new issue #${newIssue.number}`);
    }
  } catch (error) {
    console.error('Error creating/updating issue:', error.message);
    throw error;
  }
}

async function main() {
  const report = await loadNewBounties();
  
  if (!report || report.count === 0) {
    console.log('No new bounties to report');
    return;
  }
  
  await createOrUpdateIssue(report.bounties);
  console.log('✨ Issue created/updated successfully!');
}

if (require.main === module) {
  main()
    .then(() => process.exit(0))
    .catch(error => {
      console.error('❌ Error:', error);
      process.exit(1);
    });
}

module.exports = { createOrUpdateIssue };