const axios = require('axios');
const fs = require('fs').promises;
const path = require('path');

const NEW_BOUNTIES_FILE = path.join(__dirname, '..', 'data', 'new-bounties.json');

class IssueCreator {
  constructor() {
    this.token = process.env.GITHUB_TOKEN;
    this.repo = process.env.GITHUB_REPOSITORY || 'dev-kp-eloper/BountyScout';
  }

  async loadNewBounties() {
    try {
      const data = await fs.readFile(NEW_BOUNTIES_FILE, 'utf8');
      return JSON.parse(data);
    } catch (error) {
      if (error.code === 'ENOENT') {
        console.log('No new bounties file found');
        return [];
      }
      throw error;
    }
  }

  formatBountyList(bounties) {
    if (bounties.length === 0) {
      return 'No new bounties found.';
    }

    let markdown = '## 🎯 New Bug Bounty Opportunities\n\n';
    markdown += `Found **${bounties.length}** new bounty ${bounties.length === 1 ? 'opportunity' : 'opportunities'}!\n\n`;

    // Group by platform
    const byPlatform = {};
    bounties.forEach(bounty => {
      if (!byPlatform[bounty.platform]) {
        byPlatform[bounty.platform] = [];
      }
      byPlatform[bounty.platform].push(bounty);
    });

    for (const [platform, platformBounties] of Object.entries(byPlatform)) {
      markdown += `### ${platform} (${platformBounties.length})\n\n`;
      
      platformBounties.forEach(bounty => {
        markdown += `#### ${bounty.title}\n`;
        markdown += `- **Company:** ${bounty.company}\n`;
        markdown += `- **Bounty Range:** $${bounty.minBounty} - $${bounty.maxBounty}\n`;
        markdown += `- **URL:** [View Program](${bounty.url})\n`;
        markdown += `- **Discovered:** ${new Date(bounty.discoveredAt).toLocaleString()}\n\n`;
      });
    }

    markdown += '\n---\n';
    markdown += '\n*This issue was automatically generated by BountyScout*\n';

    return markdown;
  }

  async createIssue(bounties) {
    if (!this.token) {
      console.error('GITHUB_TOKEN not found');
      return;
    }

    if (bounties.length === 0) {
      console.log('No new bounties to report');
      return;
    }

    const title = `🎯 Bounty Alert: ${bounties.length} New ${bounties.length === 1 ? 'Opportunity' : 'Opportunities'} Found`;
    const body = this.formatBountyList(bounties);

    try {
      const [owner, repo] = this.repo.split('/');
      const url = `https://api.github.com/repos/${owner}/${repo}/issues`;

      const response = await axios.post(
        url,
        {
          title,
          body,
          labels: ['bounty-alert', 'automated']
        },
        {
          headers: {
            'Authorization': `token ${this.token}`,
            'Accept': 'application/vnd.github.v3+json',
            'Content-Type': 'application/json'
          }
        }
      );

      console.log(`Issue created successfully: ${response.data.html_url}`);
      return response.data;
    } catch (error) {
      console.error('Error creating issue:', error.response?.data || error.message);
      throw error;
    }
  }

  async run() {
    try {
      const bounties = await this.loadNewBounties();
      await this.createIssue(bounties);
    } catch (error) {
      console.error('Error in IssueCreator:', error.message);
      throw error;
    }
  }
}

if (require.main === module) {
  const creator = new IssueCreator();
  creator.run()
    .then(() => {
      console.log('Issue creation completed');
      process.exit(0);
    })
    .catch(error => {
      console.error('Issue creation failed:', error);
      process.exit(1);
    });
}

module.exports = IssueCreator;