const { Octokit } = require('@octokit/rest');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

const DATA_FILE = path.join(__dirname, '..', 'data', 'bounties.json');
const ISSUE_TRACKER_FILE = path.join(__dirname, '..', 'data', 'reported-issues.json');

// Load bounties data
function loadBounties() {
  try {
    if (fs.existsSync(DATA_FILE)) {
      const data = fs.readFileSync(DATA_FILE, 'utf8');
      return JSON.parse(data);
    }
  } catch (error) {
    console.error('Error loading bounties:', error.message);
  }
  return { bounties: [], lastChecked: null, newCount: 0 };
}

// Load reported issues tracker
function loadReportedIssues() {
  try {
    if (fs.existsSync(ISSUE_TRACKER_FILE)) {
      const data = fs.readFileSync(ISSUE_TRACKER_FILE, 'utf8');
      return JSON.parse(data);
    }
  } catch (error) {
    console.error('Error loading reported issues:', error.message);
  }
  return { lastReportedDate: null, reportedBountyIds: [] };
}

// Save reported issues tracker
function saveReportedIssues(data) {
  try {
    const dataDir = path.dirname(ISSUE_TRACKER_FILE);
    if (!fs.existsSync(dataDir)) {
      fs.mkdirSync(dataDir, { recursive: true });
    }
    fs.writeFileSync(ISSUE_TRACKER_FILE, JSON.stringify(data, null, 2));
  } catch (error) {
    console.error('Error saving reported issues:', error.message);
  }
}

// Create GitHub issue with bounty opportunities
async function createBountyIssue() {
  try {
    const bountiesData = loadBounties();
    const reportedData = loadReportedIssues();
    const reportedIds = new Set(reportedData.reportedBountyIds || []);

    // Filter for new bounties that haven't been reported
    const newBounties = bountiesData.bounties.filter(b => !reportedIds.has(b.id));

    if (newBounties.length === 0) {
      console.log('No new bounties to report.');
      return;
    }

    // Sort by creation date (newest first)
    newBounties.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

    // Take only the most recent bounties (limit to 20)
    const bounciesToReport = newBounties.slice(0, 20);

    // Create issue body
    let issueBody = `## 🎯 New Bounty Opportunities Found\n\n`;
    issueBody += `Found **${bounciesToReport.length}** new bounty opportunit${bounciesToReport.length === 1 ? 'y' : 'ies'}!\n\n`;
    issueBody += `Last checked: ${new Date(bountiesData.lastChecked).toLocaleString()}\n\n`;
    issueBody += `---\n\n`;

    bounciesToReport.forEach((bounty, index) => {
      issueBody += `### ${index + 1}. ${bounty.title}\n\n`;
      issueBody += `- **Repository:** ${bounty.repository}\n`;
      issueBody += `- **Created:** ${new Date(bounty.created_at).toLocaleDateString()}\n`;
      if (bounty.labels && bounty.labels.length > 0) {
        issueBody += `- **Labels:** ${bounty.labels.join(', ')}\n`;
      }
      issueBody += `- **Link:** ${bounty.url}\n\n`;
    });

    issueBody += `---\n\n`;
    issueBody += `*This issue was automatically generated by BountyScout*\n`;
    issueBody += `*Total bounties tracked: ${bountiesData.bounties.length}*`;

    // Get repository info from environment or use default
    const repoFullName = process.env.GITHUB_REPOSITORY || 'dev-kp-eloper/BountyScout';
    const [owner, repo] = repoFullName.split('/');

    // Create the issue
    const response = await octokit.issues.create({
      owner,
      repo,
      title: `🎯 Bounty Alert: ${bounciesToReport.length} New Opportunit${bounciesToReport.length === 1 ? 'y' : 'ies'} Found`,
      body: issueBody,
      labels: ['bounty-alert', 'automated']
    });

    console.log(`Created issue: ${response.data.html_url}`);

    // Update reported issues tracker
    const updatedReportedData = {
      lastReportedDate: new Date().toISOString(),
      reportedBountyIds: [...reportedIds, ...bounciesToReport.map(b => b.id)]
    };
    saveReportedIssues(updatedReportedData);

  } catch (error) {
    console.error('Error creating bounty issue:', error.message);
    if (error.response) {
      console.error('Response data:', error.response.data);
    }
    throw error;
  }
}

// Main execution
async function main() {
  try {
    console.log('Creating bounty alert issue...');
    await createBountyIssue();
    console.log('Done!');
    process.exit(0);
  } catch (error) {
    console.error('Fatal error:', error.message);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = { createBountyIssue };