const { Octokit } = require('@octokit/rest');
const fs = require('fs').promises;
const path = require('path');

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

const BOUNTY_LABELS = [
  'bounty',
  'bug-bounty',
  'reward',
  'hacktoberfest',
  'good first issue',
  'help wanted',
  'prize',
  'bounty-hunter',
  'cash-reward'
];

const DATA_DIR = path.join(__dirname, '..', 'data');
const BOUNTIES_FILE = path.join(DATA_DIR, 'bounties.json');
const LAST_RUN_FILE = path.join(DATA_DIR, 'last-run.json');

async function ensureDataDir() {
  try {
    await fs.mkdir(DATA_DIR, { recursive: true });
  } catch (error) {
    console.error('Error creating data directory:', error);
  }
}

async function loadExistingBounties() {
  try {
    const data = await fs.readFile(BOUNTIES_FILE, 'utf8');
    return JSON.parse(data);
  } catch (error) {
    return [];
  }
}

async function loadLastRun() {
  try {
    const data = await fs.readFile(LAST_RUN_FILE, 'utf8');
    return JSON.parse(data);
  } catch (error) {
    return { lastRun: null, lastIssueId: null };
  }
}

async function saveLastRun(data) {
  await fs.writeFile(LAST_RUN_FILE, JSON.stringify(data, null, 2));
}

async function saveBounties(bounties) {
  await fs.writeFile(BOUNTIES_FILE, JSON.stringify(bounties, null, 2));
}

async function searchBounties() {
  const allBounties = [];
  const seenIds = new Set();

  for (const label of BOUNTY_LABELS) {
    try {
      console.log(`Searching for issues with label: ${label}`);
      
      const response = await octokit.search.issuesAndPullRequests({
        q: `label:"${label}" is:issue is:open sort:created-desc`,
        per_page: 100
      });

      for (const issue of response.data.items) {
        if (seenIds.has(issue.id)) continue;
        
        seenIds.add(issue.id);
        
        const bountyInfo = {
          id: issue.id,
          title: issue.title,
          url: issue.html_url,
          repository: issue.repository_url.replace('https://api.github.com/repos/', ''),
          labels: issue.labels.map(l => l.name),
          state: issue.state,
          createdAt: issue.created_at,
          updatedAt: issue.updated_at,
          body: issue.body || '',
          author: issue.user.login,
          comments: issue.comments
        };

        allBounties.push(bountyInfo);
      }

      await new Promise(resolve => setTimeout(resolve, 1000));
    } catch (error) {
      console.error(`Error searching for label ${label}:`, error.message);
    }
  }

  return allBounties;
}

function findNewBounties(currentBounties, existingBounties) {
  const existingIds = new Set(existingBounties.map(b => b.id));
  return currentBounties.filter(b => !existingIds.has(b.id));
}

async function createIssueForNewBounties(newBounties) {
  if (newBounties.length === 0) {
    console.log('No new bounties found.');
    return;
  }

  const repoInfo = process.env.GITHUB_REPOSITORY || 'dev-kp-eloper/BountyScout';
  const [owner, repo] = repoInfo.split('/');

  const title = `🎯 Bounty Alert: ${newBounties.length} New Opportunit${newBounties.length === 1 ? 'y' : 'ies'} Found`;
  
  let body = `## 🎉 New Bounty Opportunities Discovered!\n\n`;
  body += `Found **${newBounties.length}** new bounty opportunit${newBounties.length === 1 ? 'y' : 'ies'}!\n\n`;
  body += `---\n\n`;

  for (let i = 0; i < Math.min(newBounties.length, 20); i++) {
    const bounty = newBounties[i];
    body += `### ${i + 1}. ${bounty.title}\n\n`;
    body += `- **Repository:** [${bounty.repository}](https://github.com/${bounty.repository})\n`;
    body += `- **Issue:** ${bounty.url}\n`;
    body += `- **Labels:** ${bounty.labels.join(', ')}\n`;
    body += `- **Created:** ${new Date(bounty.createdAt).toLocaleDateString()}\n`;
    body += `- **Author:** @${bounty.author}\n`;
    
    if (bounty.body && bounty.body.length > 0) {
      const preview = bounty.body.substring(0, 200).replace(/\n/g, ' ');
      body += `- **Description:** ${preview}${bounty.body.length > 200 ? '...' : ''}\n`;
    }
    
    body += `\n---\n\n`;
  }

  if (newBounties.length > 20) {
    body += `\n_... and ${newBounties.length - 20} more! Check the [bounties.json](./data/bounties.json) file for the complete list._\n`;
  }

  body += `\n\n**Last Updated:** ${new Date().toISOString()}\n`;
  body += `\n_This issue was automatically generated by BountyScout 🤖_`;

  try {
    await octokit.issues.create({
      owner,
      repo,
      title,
      body,
      labels: ['bounty-alert', 'automated']
    });
    console.log(`Created issue: ${title}`);
  } catch (error) {
    console.error('Error creating issue:', error.message);
  }
}

async function main() {
  try {
    console.log('Starting Bounty Scout...');
    
    await ensureDataDir();
    
    const existingBounties = await loadExistingBounties();
    console.log(`Loaded ${existingBounties.length} existing bounties`);
    
    const currentBounties = await searchBounties();
    console.log(`Found ${currentBounties.length} total bounties`);
    
    const newBounties = findNewBounties(currentBounties, existingBounties);
    console.log(`Discovered ${newBounties.length} new bounties`);
    
    if (newBounties.length > 0) {
      await createIssueForNewBounties(newBounties);
    }
    
    const allBounties = [...existingBounties, ...newBounties];
    await saveBounties(allBounties);
    
    await saveLastRun({
      lastRun: new Date().toISOString(),
      totalBounties: allBounties.length,
      newBounties: newBounties.length
    });
    
    console.log('Bounty Scout completed successfully!');
  } catch (error) {
    console.error('Error in main:', error);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = { main, searchBounties, findNewBounties };
